import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

// TODO if the user doesn't have a profile, create an id

const Home: NextPage = () => {
  // The environment prefix will only be targeted on LOCAL and DEVELOPMENT
  const environmentPrefix = process.env.NEXT_PUBLIC_DOCUMENT_TITLE_PREFIX
  const documentTitle = 'Home'

  return (
    <div className={styles.container}>
      <Head>
        <title>{`${environmentPrefix}{documentTitle}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="og:title" content={documentTitle} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/users">
            <a>Users</a>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
