import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const SITE_TITLE = 'Customer support'

// TODO if the user doesn't have a profile, create an id

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet" />
        <meta name="og:title" content={SITE_TITLE} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/users">
            <a>Users</a>
          </Link>
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
